name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# ðŸ”´ THIS IS THE KEY FIX
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pritam-roy404
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Generate contribution snake"
