name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake (light + dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pritam-roy404
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Generate light & dark contribution snake"
